=== SemenchukovAliaxei/WEB_7/WEB7/xsd_schema.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.bsu.by"
        xmlns="http://www.bsu.by"
        elementFormDefault="qualified">

    <xs:simpleType name="Food" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vegetarian"/>
            <xs:enumeration value="vegan"/>
            <xs:enumeration value="all"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Transport" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="bus"/>
            <xs:enumeration value="plane"/>
            <xs:enumeration value="railway"/>
            <xs:enumeration value="cruiser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Voucher" abstract="true">
        <xs:sequence>
            <xs:element name="placeName" type="xs:string"/>
            <xs:element name="daysAmount" type="xs:int"/>
            <xs:element name="food" type="Food"/>
            <xs:element name="transport" type="Transport"/>
            <xs:element name="price" type="xs:int"/>
            <xs:element name="peopleAmount" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Cruise">
        <xs:complexContent>
            <xs:extension base="Voucher">
                <xs:sequence>
                    <xs:element name="cruiserName" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Excursion">
        <xs:complexContent>
            <xs:extension base="Voucher">
                <xs:sequence>
                    <xs:element name="guideName" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Shopping">
        <xs:complexContent>
            <xs:extension base="Voucher">
                <xs:sequence>
                    <xs:element name="mallName" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Therapy">
        <xs:complexContent>
            <xs:extension base="Voucher">
                <xs:sequence>
                    <xs:element name="mainProcedureName" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Vacation">
        <xs:complexContent>
            <xs:extension base="Voucher">
                <xs:sequence>
                    <xs:element name="hotelName" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="VouchersList">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="shopping" type="Shopping"/>
                    <xs:element name="cruise" type="Cruise"/>
                    <xs:element name="therapy" type="Therapy"/>
                    <xs:element name="vacation" type="Vacation"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== SemenchukovAliaxei/WEB_7/WEB7/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<VouchersList
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.bsu.by"
        xsi:schemaLocation="http://www.bsu.by xsd_schema.xsd">

    <cruise>
        <placeName>Malta</placeName>
        <daysAmount>5</daysAmount>
        <food>all</food>
        <transport>cruiser</transport>
        <price>100</price>
        <peopleAmount>15</peopleAmount>
        <cruiserName>Titanik</cruiserName>
    </cruise>

    <shopping>
        <placeName>Minsk</placeName>
        <daysAmount>5</daysAmount>
        <food>all</food>
        <transport>plane</transport>
        <price>12</price>
        <peopleAmount>5</peopleAmount>
        <mallName>Stolitsa</mallName>
    </shopping>

    <vacation>
        <placeName>Hawaii</placeName>
        <daysAmount>10</daysAmount>
        <food>vegan</food>
        <transport>plane</transport>
        <price>10</price>
        <peopleAmount>2</peopleAmount>
        <hotelName>Centr</hotelName>
    </vacation>

    <therapy>
        <placeName>Hawaii</placeName>
        <daysAmount>5</daysAmount>
        <food>vegetarian</food>
        <transport>bus</transport>
        <price>3</price>
        <peopleAmount>1</peopleAmount>
        <mainProcedureName>lungs</mainProcedureName>
    </therapy>

</VouchersList>
